version: '3.8'
services:
  postgres:
    image: postgres:alpine
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - 5432:5432

volumes:
  postgres_data:
networks:
  app_network:
    driver: bridge
